Repository grafana/google-sheets-datasource, pull requests merged in 2020-06, with the labels that each got.

#92 CI & E2E updates
  .gitignore
  cypress/integration/something.ts
  cypress/screenshots/expected/something.ts/chart.png
  package.json
  yarn.lock
Labels: effort/medium

#100 E2E improvement
  cypress/integration/something.ts
Labels: type/e2e

#105 Chore: Upgrade SDK
  go.mod
  go.sum
  pkg/googlesheets/googlesheets.go
  yarn.lock
Labels: type/chore

#106 Chore: Upgrade SDK
  go.mod
  go.sum
Labels: type/chore

#101 E2E improvements
  .gitignore
  cypress/integration/something.ts
  cypress/screenshots/expected/something.ts/chart.png
  cypress/tsconfig.json
  yarn.lock
Labels: type/e2e

#107 Minor E2E updates
  cypress/integration/something.ts
  cypress/tsconfig.json
  yarn.lock
Labels: type/e2e
