Repository grafana/google-sheets-datasource, pull requests merged in 2020-03, with the labels that each got.

#19 Chore: Enable style linting
  .golangci.toml
  Magefile.go
  pkg/datasource.go
  pkg/googlesheets/columndefinition/columndefinition.go
  pkg/googlesheets/googlesheets.go
  pkg/googlesheets/types.go
  yarn.lock
Labels: enhancement

#27 Back-end: Fix logging
  pkg/datasource.go
  yarn.lock
Labels: bug

#42 Added e2e test runner
  .circleci/config.yml
  .gitignore
  cypress/integration/something.ts
  cypress/tsconfig.json
  package.json
  yarn.lock
Labels: type/e2e

#52 E2E tests
  .circleci/config.yml
  cypress/integration/something.ts
  package.json
  yarn.lock
Labels: effort/x-large, type/e2e
